### ISSUE TITLE
`GradleConfigurationCacheResult.Outcome` isn't properly formatted

### ISSUE THREAD

**Issue by gabrielfeo** [gabrielfeo/develocity-api-kotlin#282]
Enum members name casing goes against the Kotlin style guide and will pollute client code. Class is only present after library v2024.2.0-alpha01.

```kotlin
    /**
     * The outcome of the configuration cache operation:   * `HIT` - There was a configuration cache hit.   * `MISS` - There was a configuration cache miss.   * `FAILED` - There was a configuration cache related failure. 
     *
     * Values: hIT,mISS,fAILED
     */
    @JsonClass(generateAdapter = false)
    enum class Outcome(val value: kotlin.String) {
        @Json(name = "HIT") hIT("HIT"),
        @Json(name = "MISS") mISS("MISS"),
        @Json(name = "FAILED") fAILED("FAILED");
    }
```

Occurs when the API spec's `enum` items are upper-case and the Kotlin generator's `enumPropertyNaming` is set to `camelCase`.

```yaml
    GradleConfigurationCacheResult:
      type: object
      description: The configuration cache result of a Gradle build.
      required:
        - outcome
      properties:
        outcome:
          type: string
          enum:
            - HIT
            - MISS
            - FAILED
          description: |
            The outcome of the configuration cache operation:
              * `HIT` - There was a configuration cache hit.
              * `MISS` - There was a configuration cache miss.
              * `FAILED` - There was a configuration cache related failure.
```

The enum casing found in the new spec is inconsistent with previous enums, like `TestOutcome`:

```yaml
    TestOutcome:
      type: string
      enum:
        - passed
        - failed
        - skipped
        - flaky
        - notSelected
```

The issue is surfaced due to the spec's inconsistency, but the cause is OpenAPI Generator's `enumPropertyNaming` implementation. The actual [`enumPropertyNaming` options](https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/kotlin.md) implementation will only convert the first char in some cases (see [`CamelizeOptions`](https://github.com/OpenAPITools/openapi-generator/blob/2bc0e5f7457615f175ba936a0093f8fc5f7ff1d2/modules/openapi-generator/src/main/java/org/openapitools/codegen/utils/CamelizeOption.java))
